apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-admin-deployment
  labels:
    app: pg-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-admin
  template:
    metadata:
      labels:
        app: pg-admin
    spec:
      containers:
      - name: pg-admin
        image: dpage/pgadmin4:6.17
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: pg-admin-secrets
              key: DB_PASSWORD
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef: 
              name: pg-admin-secrets
              key: PG_USER_EMAIL
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION #Config para evitar errores
          value: "False"
--- 
apiVersion: v1
kind: Service
metadata:
  name: pg-admin-service
spec:
  type: NodePort #Permite exponer servicio al exterior 
  selector:
    app: pg-admin
  ports:
    - protocol: TCP
      port: 80 #Cualquier puertp normaslemente se pone el mismo de la defincion superiro
      targetPort: 80
      nodePort: 30200 # En la documentacion dice que el puerto debe estar entre 30000 y 32000 algo