apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  # DB_USER: postgres --> base 64
  #echp -n postgres \ base 64
  DB_USER: cG9zdGdyZXM=
  # DB_PASSWORD: EST4ESMICL4VE
  DB_PASSWORD: RVNUNEVTTUlDTDRWRQ==